/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { sanityClient, urlFor } from "../lib/sanity";
import { RecipePreview } from "../types/recipe";

const recipesQuery = `
  *[_type == "recipe"] {
    _id,
    name,
    slug,
    mainImage
  }
`;

interface HomeProps {
  recipes: RecipePreview[];
}

const Home: NextPage<HomeProps> = ({ recipes }) => {
  return (
    <div>
      <Head>
        <title>Kitchen 👨🏽‍🍳</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to Kitchen 👨🏽‍🍳</h1>
      <ul className="recipes-list">
        {recipes?.length &&
          recipes.map((recipe) => (
            <li key={recipe._id} className="recipe-card">
              <Link href={`/recipes/${recipe.slug.current}`}>
                <a>
                  <img src={urlFor(recipe.mainImage).url()} alt={recipe.name} />
                  <span>{recipe.name}</span>
                </a>
              </Link>
            </li>
          ))}
      </ul>
    </div>
  );
};

export default Home;

export const getStaticProps = async () => {
  const recipes = await sanityClient.fetch(recipesQuery);

  return { props: { recipes } };
};
